OPENQASM 2.1;
include "qelib1.inc";

operator xx a,b {
    x a, x b;
}
operator yy a,b {
    y a, y b;
}
operator zz a,b {
    z a, z b;
}

operator xxz_energy_operator_open a, b, c, d, e, f, g, h {
    zz a,b;
    zz b,c;
    zz c,d;
    zz d,e;
    zz e,f;
    zz f,g;
    zz g,h;
    yy a,b;
    yy b,c;
    yy c,d;
    yy d,e;
    yy e,f;
    yy f,g;
    yy g,h;
    xx a,b;
    xx b,c;
    xx c,d;
    xx d,e;
    xx e,f;
    xx f,g;
    xx g,h;
}


operator xxz_energy_operator_closed a, b, c, d, e, f, g, h {
    zz a,b;
    zz b,c;
    zz c,d;
    zz d,e;
    zz e,f;
    zz f,g;
    zz g,h;
    yy a,b;
    yy b,c;
    yy c,d;
    yy d,e;
    yy e,f;
    yy f,g;
    yy g,h;
    xx a,b;
    xx b,c;
    xx c,d;
    xx d,e;
    xx e,f;
    xx f,g;
    xx g,h;
    zz h,a;
    yy h,a;
    xx h,a;
}


gate xxz_circuit_closed(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) a, b, c, d, e, f, g, h {
    h a;
    h c;
    h e;
    h g;
    cx a,b;
    cx c,d;
    cx e,f;
    cx g,h;
    zz(t0) b,c;
    yy(t4) b,c;
    xx(t4) b,c;
    zz(t0) d,e;
    yy(t4) d,e;
    xx(t4) d,e;
    zz(t0) f,g;
    yy(t4) f,g;
    xx(t4) f,g;
    zz(t0) h,a;
    yy(t4) h,a;
    xx(t4) h,a;
    zz(t8) b,c;
    yy(t12) b,c;
    xx(t12) b,c;
    zz(t8) d,e;
    yy(t12) d,e;
    xx(t12) d,e;
    zz(t8) f,g;
    yy(t12) f,g;
    xx(t12) f,g;
    zz(t1) b,c;
    yy(t5) b,c;
    xx(t5) b,c;
    zz(t1) d,e;
    yy(t5) d,e;
    xx(t5) d,e;
    zz(t1) f,g;
    yy(t5) f,g;
    xx(t5) f,g;
    zz(t1) h,a;
    yy(t5) h,a;
    xx(t5) h,a;
    zz(t9) b,c;
    yy(t13) b,c;
    xx(t13) b,c;
    zz(t9) d,e;
    yy(t13) d,e;
    xx(t13) d,e;
    zz(t9) f,g;
    yy(t13) f,g;
    xx(t13) f,g;
    zz(t2) b,c;
    yy(t6) b,c;
    xx(t6) b,c;
    zz(t2) d,e;
    yy(t6) d,e;
    xx(t6) d,e;
    zz(t2) f,g;
    yy(t6) f,g;
    xx(t6) f,g;
    zz(t2) h,a;
    yy(t6) h,a;
    xx(t6) h,a;
    zz(t10) b,c;
    yy(t14) b,c;
    xx(t14) b,c;
    zz(t10) d,e;
    yy(t14) d,e;
    xx(t14) d,e;
    zz(t10) f,g;
    yy(t14) f,g;
    xx(t14) f,g;
    zz(t3) b,c;
    yy(t7) b,c;
    xx(t7) b,c;
    zz(t3) d,e;
    yy(t7) d,e;
    xx(t7) d,e;
    zz(t3) f,g;
    yy(t7) f,g;
    xx(t7) f,g;
    zz(t3) h,a;
    yy(t7) h,a;
    xx(t7) h,a;
    zz(t11) b,c;
    yy(t15) b,c;
    xx(t15) b,c;
    zz(t11) d,e;
    yy(t15) d,e;
    xx(t15) d,e;
    zz(t11) f,g;
    yy(t15) f,g;
    xx(t15) f,g;
}

gate xxz_circuit_open(t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12, t13, t14, t15) a, b, c, d, e, f, g, h {
    h a;
    h c;
    h e;
    h g;
    cx a,b;
    cx c,d;
    cx e,f;
    cx g,h;
    zz(t0) b,c;
    yy(t4) b,c;
    xx(t4) b,c;
    zz(t0) d,e;
    yy(t4) d,e;
    xx(t4) d,e;
    zz(t0) f,g;
    yy(t4) f,g;
    xx(t4) f,g;
    zz(t8) b,c;
    yy(t12) b,c;
    xx(t12) b,c;
    zz(t8) d,e;
    yy(t12) d,e;
    xx(t12) d,e;
    zz(t8) f,g;
    yy(t12) f,g;
    xx(t12) f,g;
    zz(t1) b,c;
    yy(t5) b,c;
    xx(t5) b,c;
    zz(t1) d,e;
    yy(t5) d,e;
    xx(t5) d,e;
    zz(t1) f,g;
    yy(t5) f,g;
    xx(t5) f,g;
    zz(t9) b,c;
    yy(t13) b,c;
    xx(t13) b,c;
    zz(t9) d,e;
    yy(t13) d,e;
    xx(t13) d,e;
    zz(t9) f,g;
    yy(t13) f,g;
    xx(t13) f,g;
    zz(t2) b,c;
    yy(t6) b,c;
    xx(t6) b,c;
    zz(t2) d,e;
    yy(t6) d,e;
    xx(t6) d,e;
    zz(t2) f,g;
    yy(t6) f,g;
    xx(t6) f,g;
    zz(t10) b,c;
    yy(t14) b,c;
    xx(t14) b,c;
    zz(t10) d,e;
    yy(t14) d,e;
    xx(t14) d,e;
    zz(t10) f,g;
    yy(t14) f,g;
    xx(t14) f,g;
    zz(t3) b,c;
    yy(t7) b,c;
    xx(t7) b,c;
    zz(t3) d,e;
    yy(t7) d,e;
    xx(t7) d,e;
    zz(t3) f,g;
    yy(t7) f,g;
    xx(t7) f,g;
    zz(t11) b,c;
    yy(t15) b,c;
    xx(t15) b,c;
    zz(t11) d,e;
    yy(t15) d,e;
    xx(t15) d,e;
    zz(t11) f,g;
    yy(t15) f,g;
    xx(t15) f,g;
}
